# Generated by Django 5.0.3 on 2024-03-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user_image'),
        ),
    ]
